SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MIN_LUMP_FACTOR = 0.8
ASTEROID_MAX_LUMP_FACTOR = 1.2
ASTEROID_MIN_NUM_SEGMENTS = 10
ASTEROID_MAX_NUM_SEGMENTS = 20


PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_BLINK_PERIOD = 0.15

SHOT_RADIUS = 5